version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    build:
      context: ./backend
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./database:/db