# Use a lightweight base image
FROM alpine:latest

# Install SQLite
RUN apk update && apk add sqlite

# Set the working directory
WORKDIR /db

# Command to run when the container starts
CMD ["sqlite3"]
